# Drawing Conclusions Using Groupby

Use `winequality_edited.csv`. You should've created this data file in the previous section: *Appending Data (cont.)*.

In [2]:
# Load dataset
import pandas as pd
df = pd.read_csv('winequality_edited.csv')
df.head()

,alcohol,chlorides,citric_acid,color,density,fixed_acidity,free_sulfur_dioxide,pH,quality,residual_sugar,sulphates,total_sulfur-dioxide,total_sulfur_dioxide,volatile_acidity
0,9.4,0.076,0.00,red,0.9978,7.4,11.0,3.51,5,1.9,0.56,34.0,NaN,0.70
1,9.8,0.098,0.00,red,0.9968,7.8,25.0,3.20,5,2.6,0.68,67.0,NaN,0.88
2,9.8,0.092,0.04,red,0.9970,7.8,15.0,3.26,5,2.3,0.65,54.0,NaN,0.76
3,9.8,0.075,0.56,red,0.9980,11.2,17.0,3.16,6,1.9,0.58,60.0,NaN,0.28
4,9.4,0.076,0.00,red,0.9978,7.4,11.0,3.51,5,1.9,0.56,34.0,NaN,0.70

### Is a certain type of wine associated with higher quality?

In [3]:
# Find the mean quality of each wine type (red and white) with groupby
df.groupby('quality').mean()

,alcohol,chlorides,citric_acid,density,fixed_acidity,free_sulfur_dioxide,pH,residual_sugar,sulphates,total_sulfur-dioxide,total_sulfur_dioxide,volatile_acidity
quality,,,,,,,,,,,,
3,10.215000,0.077033,0.281000,0.995744,7.853333,39.216667,3.257667,5.140000,0.506333,24.900000,170.600000,0.517000
4,10.180093,0.060056,0.272315,0.994833,7.288889,20.636574,3.231620,4.153704,0.505648,36.245283,125.279141,0.457963
5,9.837783,0.064666,0.307722,0.995849,7.326801,30.237371,3.212189,5.804116,0.526403,56.513950,150.904598,0.389614
6,10.587553,0.054157,0.323583,0.994558,7.177257,31.165021,3.217726,5.549753,0.532549,40.869906,137.047316,0.313863
7,11.386006,0.045272,0.334764,0.993126,7.128962,30.422150,3.228072,4.731696,0.547025,35.020101,125.114773,0.288800
8,11.678756,0.041124,0.332539,0.992514,6.835233,34.533679,3.223212,5.382902,0.512487,33.444444,126.165714,0.291010
9,12.180000,0.027400,0.386000,0.991460,7.420000,33.400000,3.308000,4.120000,0.466000,NaN,116.000000,0.298000

### What level of acidity receives the highest average rating?

In [5]:
# View the min, 25%, 50%, 75%, max pH values with Pandas describe
df['pH'].describe()

count    6497.000000
mean        3.218501
std         0.160787
min         2.720000
25%         3.110000
50%         3.210000
75%         3.320000
max         4.010000
Name: pH, dtype: float64

In [7]:
# Bin edges that will be used to "cut" the data into groups
bin_edges = [2.720000 ,3.110000 ,3.210000 ,3.320000 ,4.010000 ] # Fill in this list with five values you just found

In [8]:
# Labels for the four acidity level groups
bin_names = ['Lv1','Lv2' ,'Lv3' ,'Lv4' ] # Name each acidity level category

In [9]:
# Creates acidity_levels column
df['acidity_levels'] = pd.cut(df['pH'], bin_edges, labels=bin_names)

# Checks for successful creation of this column
df.head()

,alcohol,chlorides,citric_acid,color,density,fixed_acidity,free_sulfur_dioxide,pH,quality,residual_sugar,sulphates,total_sulfur-dioxide,total_sulfur_dioxide,volatile_acidity,acidity_levels
0,9.4,0.076,0.00,red,0.9978,7.4,11.0,3.51,5,1.9,0.56,34.0,NaN,0.70,Lv4
1,9.8,0.098,0.00,red,0.9968,7.8,25.0,3.20,5,2.6,0.68,67.0,NaN,0.88,Lv2
2,9.8,0.092,0.04,red,0.9970,7.8,15.0,3.26,5,2.3,0.65,54.0,NaN,0.76,Lv3
3,9.8,0.075,0.56,red,0.9980,11.2,17.0,3.16,6,1.9,0.58,60.0,NaN,0.28,Lv2
4,9.4,0.076,0.00,red,0.9978,7.4,11.0,3.51,5,1.9,0.56,34.0,NaN,0.70,Lv4

In [21]:
# Find the mean quality of each acidity level with groupby
df.groupby('acidity_levels').mean()

,alcohol,chlorides,citric_acid,density,fixed_acidity,free_sulfur_dioxide,pH,quality,residual_sugar,sulphates,total_sulfur-dioxide,total_sulfur_dioxide,volatile_acidity
acidity_levels,,,,,,,,,,,,,
Lv1,10.330208,0.055131,0.370792,0.994708,7.543914,33.179965,3.029062,5.783343,7.088876,0.503937,50.111888,137.146125,0.294683
Lv2,10.391073,0.054666,0.340548,0.994697,7.365064,33.229154,3.164833,5.784540,5.931984,0.509300,47.921708,143.092878,0.318551
Lv3,10.610369,0.055715,0.313585,0.994476,7.143566,28.983995,3.267010,5.850832,4.721159,0.541287,49.702032,135.521448,0.346751
Lv4,10.656057,0.058777,0.243901,0.994899,6.769949,26.327510,3.433348,5.859593,3.848983,0.574136,43.240437,136.716746,0.403815

In [17]:
# Save changes for the next section
df.to_csv('winequality_edited.csv', index=False)

In [18]:
df.groupby('color').mean()

,alcohol,chlorides,citric_acid,density,fixed_acidity,free_sulfur_dioxide,pH,quality,residual_sugar,sulphates,total_sulfur-dioxide,total_sulfur_dioxide,volatile_acidity
color,,,,,,,,,,,,,
red,10.422983,0.087467,0.270976,0.996747,8.319637,15.874922,3.311113,5.636023,2.538806,0.658149,46.467792,NaN,0.527821
white,10.514267,0.045772,0.334192,0.994027,6.854788,35.308085,3.188267,5.877909,6.391415,0.489847,NaN,138.360657,0.278241